import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Index from "./components/Index";
import Footer from "./components/Footer";
import IndexProject from "./components/IndexProject";
import Expertise from "./components/Expertise";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Samuel Din Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" px-10 md:px-20 lg:px-40">
        <Navbar />
        <Index />
        <IndexProject />
        <Expertise />
      </main>
      <Footer />
    </>
  );
}
